name: 4-Call Reusable Workflow Templates

on:
  push:
     branches: [main]
  workflow_dispatch: 

jobs:
  call_dependencies_workflow_job:
    needs: call_reusable_workflow_job
    uses: amikshas/gh-abcs-actions-practice/.github/workflows/job-dependencies.yml@main
